### ISSUE TITLE
Running the server on CentOS 6

### ISSUE THREAD

**Issue by Crytek** [SunDwarf/OWAPI#104] opened 2016-10-15 11:36 UTC
I am trying to install the server on Linux CentOS 6.
I have installed all the requirements. Python 3.5.2... Redis....
for some reason when I am trying to use the command `PYTHONPATH=. asphalt run config.yml`
I am facing an issue.
asphalt isn't a recognized command in my system for some reason.
this might be me not knowing the commands as I should, but i would appriciate if you can help in this matter. 
thank you!

**Comment by Crytek** [comment] 2016-10-15 12:32
Ok, I sorted the "asphalt is not a command" issue, but not it tells me that config.yml doesn't exits "Could not open file: config.yml: No such file or directory".

**Comment by mikevb1** [comment] 2016-10-15 20:03
SunDwarf seems to have removed `config.yml` (see https://github.com/SunDwarf/OWAPI/commit/af4bc4faccd12aaca7179997d78daaf2cfcd283c). Add it back yourself or use the noredis config.

**Comment by SunDwarf** [comment] 2016-10-15 20:03
Where did the default config go

**Comment by Crytek** [comment] 2016-10-16 07:18
now everything runs! but for some reason i get "connection refused" error when I am trying to load it from the browser...

**Comment by SunDwarf** [comment] 2016-10-16 11:13
Is there anything else that appears in the console in the first error?

**Comment by Crytek** [comment] 2016-10-16 11:17
```
OWAPI]# PYTHONPATH=. asphalt run -l uvloop config.yml
2016-10-16 13:15:49,993 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v2 with 10 new routes
2016-10-16 13:15:49,994 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v3 with 6 new routes
2016-10-16 13:15:50,003 - [INFO] Kyoukai.Blueprint.owapi -> Registered Blueprint api with 16 new routes
Traceback (most recent call last):
  File "/home/owapi/OWAPI/venv/bin/asphalt", line 11, in <module>
    sys.exit(main())
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/asphalt/core/command.py", line 39, in run
    run_application(component, **config_data)
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/asphalt/core/runner.py", line 72, in run_application
    policy = create_policy()
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/asphalt/core/runner.py", line 20, in uvloop_policy
    import uvloop
ImportError: No module named 'uvloop'
```

This is the first one when trying to load the command `PYTHONPATH=. asphalt run -l uvloop config.yml`

**Comment by Crytek** [comment] 2016-10-16 11:20
regarding this warnings:
`2016-10-16 09:34:26,390 - [WARNING] Kyoukai -> Exception happened during HTTP parsing.
2016-10-16 09:34:26,390 - [WARNING] Kyoukai -> This is not necessarily a bug`

I am not getting any errors or warning before hand.. I just get those warnings, and no data output.

**Comment by SunDwarf** [comment] 2016-10-16 11:34
The first one is due to not having uvloop installed, but the second one I have no idea about.

**Comment by Crytek** [comment] 2016-10-16 11:44
can you install the server on my vps? I will pay if needed, it's just crucial to me that this will work on my server.

**Comment by SunDwarf** [comment] 2016-10-16 11:46
Can you try connecting to your instance via curl?

**Comment by Crytek** [comment] 2016-10-16 11:50
yup, that's the first thing we tried.

**Comment by SunDwarf** [comment] 2016-10-16 11:51
Does curl work when you connect locally, on the same VPS?

**Comment by Crytek** [comment] 2016-10-16 11:54
I guess it should work... We tried to connect curl to your server and it does pull data.
so if it works from a remote server, it should work locally...

**Comment by SunDwarf** [comment] 2016-10-16 11:55
Inside the virtual environment, can you try this command:

`pip install git+https://github.com/SunDwarf/Kyoukai.git` and then re-run

**Comment by Crytek** [comment] 2016-10-16 12:00
code:
```
<?php
require_once( 'wp-load.php' );
require_once( 'wp-includes/wp-db.php' );
require( 'simple_html_dom.php' );

function getOWAPI( $url ) {
	$ch = curl_init( $url );
	curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
	curl_setopt( $ch, CURLOPT_BINARYTRANSFER, true );
	curl_setopt( $ch, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT'] );
	$data = curl_exec( $ch );
	curl_close( $ch );

	return $data;
}

$data          = getOWAPI( "https://localhost:4444/api/v3/u/DangerZone-21292/blob" );
$data          = str_replace( 'd.va', 'dva', $data );
$result        = json_decode( $data );
$heroStats     = $result->eu->heroes->stats->competitive;
$overall_stats = $result->eu->stats->competitive->overall_stats;
$game_stats    = $result->eu->stats->competitive->game_stats;

$comprank = $overall_stats->comprank;
$wins     = $overall_stats->wins;
$level    = ( $overall_stats->prestige * 100 ) + $overall_stats->level;
$avatar   = $overall_stats->avatar;
    
echo var_dump($data);
echo var_dump($result);

?>

```
result: `string(0) "" NULL`

I ran the command.. then re-run the server... still same output as above.

**Comment by azah** [comment] 2016-10-16 12:03
Uh are you running OWAPI locally when you run that?

**Comment by Crytek** [comment] 2016-10-16 12:05
`$data = getOWAPI( "https://localhost:4444/api/v3/u/DangerZone-21292/blob" );`

That runs trough localhost...

**Comment by azah** [comment] 2016-10-16 12:07
Yes,  but are you actually running OWAPI yourself and have it at `localhost:4444`? It won't do anything if you're not

**Comment by Crytek** [comment] 2016-10-16 12:10
I don't understand, but ill try to break it down.
I am running OWAPI from my server ssh via the command `PYTHONPATH=. asphalt run config.yml`
The output i get is this:
```
2016-10-16 14:07:54,769 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v2 with 10 new routes
2016-10-16 14:07:54,770 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v3 with 6 new routes
2016-10-16 14:07:54,774 - [INFO] Kyoukai.Blueprint.owapi -> Registered Blueprint api with 16 new routes
2016-10-16 14:07:54,782 - [INFO] asphalt.core.runner -> Starting application
2016-10-16 14:07:54,871 - [INFO] asphalt.redis.component -> Configured Redis client (default / ctx.redis; address=('127.0.0.1', 6379), db=1)
2016-10-16 14:07:54,871 - [INFO] Kyoukai -> Kyoukai serving on 127.0.0.1:4444.
2016-10-16 14:07:54,871 - [INFO] OWAPI -> Started OWAPI server.

```
127.0.0.1 is in fact localhost, so that should work... right?

**Comment by azah** [comment] 2016-10-16 12:13
Use http not https

**Comment by Crytek** [comment] 2016-10-16 12:17
```
^C2016-10-16 14:07:52,416 - [INFO] asphalt.redis.component -> Redis client (default) shut down
2016-10-16 14:07:52,417 - [INFO] asphalt.core.runner -> Application stopped
(venv) [root@vps324083 OWAPI]# PYTHONPATH=. asphalt run config.yml
2016-10-16 14:07:54,769 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v2 with 10 new routes
2016-10-16 14:07:54,770 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v3 with 6 new routes
2016-10-16 14:07:54,774 - [INFO] Kyoukai.Blueprint.owapi -> Registered Blueprint api with 16 new routes
2016-10-16 14:07:54,782 - [INFO] asphalt.core.runner -> Starting application
2016-10-16 14:07:54,871 - [INFO] asphalt.redis.component -> Configured Redis client (default / ctx.redis; addre   ss=('127.0.0.1', 6379), db=1)
2016-10-16 14:07:54,871 - [INFO] Kyoukai -> Kyoukai serving on 127.0.0.1:4444.
2016-10-16 14:07:54,871 - [INFO] OWAPI -> Started OWAPI server.
(venv) [root@vps324083 OWAPI]# PYTHONPATH=. asphalt run config.yml
2016-10-16 14:07:54,769 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v2 with 10 new routes
2016-10-16 14:07:54,770 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v3 with 6 new routes
2016-10-16 14:07:54,774 - [INFO] Kyoukai.Blueprint.owapi -> Registered Blueprint api with 16 new routes
2016-10-16 14:07:54,782 - [INFO] asphalt.core.runner -> Starting application
2016-10-16 14:07:54,871 - [INFO] asphalt.redis.component -> Configured Redis client (default / ctx.redis; addre   ss=('127.0.0.1', 6379), db=1)
2016-10-16 14:07:54,871 - [INFO] Kyoukai -> Kyoukai serving on 127.0.0.1:4444.
2016-10-16 14:07:54,871 - [INFO] OWAPI -> Started OWAPI server.


2016-10-16 14:07:54,769 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v2 with 10 new routes
2016-10-16 14:07:54,770 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v3 with 6 new routes
2016-10-16 14:07:54,774 - [INFO] Kyoukai.Blueprint.owapi -> Registered Blueprint api with 16 new routes
2016-10-16 14:07:54,782 - [INFO] asphalt.core.runner -> Starting application
2016-10-16 14:07:54,871 - [INFO] asphalt.redis.component -> Configured Redis client (default / ctx.redis; addre   ss=('127.0.0.1', 6379), db=1)
2016-10-16 14:07:54,871 - [INFO] Kyoukai -> Kyoukai serving on 127.0.0.1:4444.
2016-10-16 14:07:54,871 - [INFO] OWAPI -> Started OWAPI server.
2016-10-16 14:11:21,110 - [WARNING] Kyoukai -> Exception happened during HTTP parsing.
2016-10-16 14:11:21,110 - [WARNING] Kyoukai -> This is not necessarily a bug.
^C2016-10-16 14:13:59,280 - [INFO] asphalt.redis.component -> Redis client (default) shut down
2016-10-16 14:13:59,281 - [INFO] asphalt.core.runner -> Application stopped
(venv) [root@vps324083 OWAPI]# nc -l 8888
-bash: nc: command not found
(venv) [root@vps324083 OWAPI]# PYTHONPATH=. asphalt run config.yml
2016-10-16 14:14:46,916 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v2 with 10 new routes
2016-10-16 14:14:46,916 - [INFO] Kyoukai.Blueprint.api -> Registered Blueprint api_v3 with 6 new routes
2016-10-16 14:14:46,921 - [INFO] Kyoukai.Blueprint.owapi -> Registered Blueprint api with 16 new routes
2016-10-16 14:14:46,930 - [INFO] asphalt.core.runner -> Starting application
2016-10-16 14:14:47,032 - [INFO] asphalt.redis.component -> Configured Redis client (default / ctx.redis; addre   ss=('127.0.0.1', 6379), db=1)
2016-10-16 14:14:47,032 - [INFO] Kyoukai -> Kyoukai serving on 127.0.0.1:4444.
2016-10-16 14:14:47,032 - [INFO] OWAPI -> Started OWAPI server.
2016-10-16 14:14:50,397 - [WARNING] Kyoukai -> Exception happened during HTTP parsing.
2016-10-16 14:14:50,397 - [WARNING] Kyoukai -> This is not necessarily a bug.
2016-10-16 14:15:10,734 - [INFO] OWAPI -> Cache miss for `_real_get_body('https://playoverwatch.com/en-us/caree   r/pc/eu/DangerZone-21292',)`
2016-10-16 14:15:10,735 - [INFO] OWAPI -> GET => https://playoverwatch.com/en-us/career/pc/eu/DangerZone-21292
2016-10-16 14:15:10,754 - [INFO] OWAPI -> Cache miss for `_real_get_body('https://playoverwatch.com/en-us/caree   r/pc/us/DangerZone-21292',)`
2016-10-16 14:15:10,755 - [INFO] OWAPI -> GET => https://playoverwatch.com/en-us/career/pc/us/DangerZone-21292
2016-10-16 14:15:10,770 - [INFO] OWAPI -> Cache miss for `_real_get_body('https://playoverwatch.com/en-us/caree   r/pc/kr/DangerZone-21292',)`
2016-10-16 14:15:10,770 - [INFO] OWAPI -> GET => https://playoverwatch.com/en-us/career/pc/kr/DangerZone-21292
2016-10-16 14:15:12,429 - [INFO] OWAPI -> GET => https://playoverwatch.com/en-us/career/pc/us/DangerZone-21292    => 200
2016-10-16 14:15:12,605 - [INFO] OWAPI -> Storing _real_get_body('https://playoverwatch.com/en-us/career/pc/us/   DangerZone-21292',) with expiration 300
2016-10-16 14:15:12,637 - [INFO] OWAPI -> GET => https://playoverwatch.com/en-us/career/pc/kr/DangerZone-21292    => 404
2016-10-16 14:15:12,637 - [INFO] OWAPI -> Storing _real_get_body('https://playoverwatch.com/en-us/career/pc/kr/   DangerZone-21292',) with expiration 300
2016-10-16 14:15:18,570 - [INFO] OWAPI -> GET => https://playoverwatch.com/en-us/career/pc/eu/DangerZone-21292    => 200
2016-10-16 14:15:18,745 - [INFO] OWAPI -> Storing _real_get_body('https://playoverwatch.com/en-us/career/pc/eu/   DangerZone-21292',) with expiration 300
2016-10-16 14:15:18,970 - [INFO] Kyoukai -> HTTP/1.1 GET /api/v3/u/DangerZone-21292/blob - 500
2016-10-16 14:15:18,971 - [ERROR] OWAPI -> Unhandled exception - Blizzard format probably changed!
Traceback (most recent call last):
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/kyoukai/app.py", line 526, in delegate_request
    response = await route.invoke(ctx)
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 162, in invoke
    result = await self._wrapped_coro(*args)
  File "/home/owapi/OWAPI/owapi/v3/v3_util.py", line 116, in _rl_inner2
    return await func(ctx, *args, **kwargs)
  File "/home/owapi/OWAPI/owapi/v3/__init__.py", line 48, in get_blob
    d["stats"]["competitive"] = parsing.bl_parse_stats(result, mode="competitive")
  File "/home/owapi/OWAPI/owapi/v3/parsing.py", line 118, in bl_parse_stats
    losses = int(misc_box.xpath(".//text()[. = 'Games Lost']/../..")[0][1].text.replace(",", ""))
IndexError: list index out of range
2016-10-16 14:15:18,975 - [ERROR] Kyoukai -> Unhandled exception in route `<Route 'get_blob' in blueprint <Blue   print 'api_v3' with 6 routes>>`:
Traceback (most recent call last):
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/kyoukai/app.py", line 526, in delegate_request
    response = await route.invoke(ctx)
  File "/home/owapi/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 162, in invoke
    result = await self._wrapped_coro(*args)
  File "/home/owapi/OWAPI/owapi/v3/v3_util.py", line 116, in _rl_inner2
    return await func(ctx, *args, **kwargs)
  File "/home/owapi/OWAPI/owapi/v3/__init__.py", line 48, in get_blob
    d["stats"]["competitive"] = parsing.bl_parse_stats(result, mode="competitive")
  File "/home/owapi/OWAPI/owapi/v3/parsing.py", line 118, in bl_parse_stats
    losses = int(misc_box.xpath(".//text()[. = 'Games Lost']/../..")[0][1].text.replace(",", ""))
IndexError: list index out of range


```

**Comment by SunDwarf** [comment] 2016-10-16 12:20
I can't reproduce this error on the official version - are you fully updated?

```
$ http HEAD https://owapi.net/api/v3/u/DangerZone-21292/blob                                                                                                                 Sun 16 Oct 2016 13:19:17 BST
HTTP/1.1 200 OK
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json
Date: Sun, 16 Oct 2016 12:20:14 GMT
Server: nginx/1.10.0 (Ubuntu)
X-Powered-By: Kyoukai
```

**Comment by SunDwarf** [comment] 2016-10-16 12:27
That should be fixed now.

**Closed** 2016-10-16 12:42 UTC
Labels: The Kraken
